### ISSUE TITLE
Malformed Api Url

### ISSUE THREAD

**Issue by deiv** [dmstocking/sick-stache#37]
The api url, is malformed, because is leaving extras "/" in the path when concatenated, example: 

http://ip:8081///api/xxxxxxxxxxxxxxxxx/?cmd=shows

**Comment by dmstocking** [comment]
That is pretty odd. I probably won't get to this for a while. If you want it fixed sooner, I will be more than glad to pull in a merge request.

**Comment by MGaetan89** [comment]
There is already one https://github.com/dmstocking/sick-stache/pull/33 :smile:

**Comment by dmstocking** [comment]
Fixed by #33. I'll try to actually build and put a new version on Google play this weekend.

**Comment by deiv** [comment]
Thx
